on:
  push:
    paths:
      - 'ci-dex/**'

name: GitHub Actions
jobs:
  review:
    runs-on: ubuntu-latest
    # container:
    #   image: docker://kauplan/review2.5
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        uses: actions/checkout@v2
        with:
          repository: srz-zumix/ci-dex-review-contents
          token: ${{ secrets.GitHub_PAT }}
          path: ci-dex/contents
      - uses: docker://kauplan/review2.5
        with:
          entrypoint: bash
          args: -c "cd ci-dex; rake pdf"
      - name: copy artifacts
        run: |
          mkdir artifacts
          cp ci-dex/ci-dex.pdf ./artifacts
      - name: Extract branch name
        id: extract_branch
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      # - uses: actions/upload-artifact@v1
      #   with:
      #     name: ci-dex
      #     path: ci-dex/ci-dex.pdf
      - name: Upload to Google Drive
        uses: satackey/action-google-drive@v1
        with:
          upload-from: ./artifacts
          upload-to: /BOOK/techbookfest/techbookfest8/${{ steps.extract_branch.outputs.branch }}
          skicka-tokencache-json: ${{ secrets.SKICKA_TOKENCACHE_JSON }}
          google-client-id: ${{ secrets.SKICKA_CLIENT_ID }}
          google-client-secret: ${{ secrets.SKICKA_CLIENT_SECRET }}
      - name: Notify slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: pullreminders/slack-action@master
        with:
          args: '{\"channel\":\"CSYR0PEHW\",\"text\":\"Upload new pdf!!\"}'
      - name: Notify slack (fail)
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: pullreminders/slack-action@master
        with:
          args: '{\"channel\":\"CSYR0PEHW\",\"text\":\"<!here> fail https://github.com/srz-zumix/techbookfest8/actions\"}'
