on: [push]

name: GitHub Actions
jobs:
  review:
    runs-on: ubuntu-latest
    # container:
    #   image: docker://kauplan/review2.5
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        uses: actions/checkout@v2
        with:
          repository: srz-zumix/ci-dex-review-contents
          token: ${{ secrets.GitHub_PAT }}
          path: ci-dex/contents
      - uses: docker://kauplan/review2.5
        with:
          entrypoint: bash
          args: -c "cd ci-dex; rake pdf"
