on: [push]

name: GitHub Actions
jobs:
  review:
    runs-on: ubuntu-latest
    # container:
    #   image: docker://kauplan/review2.5
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        uses: actions/checkout@v2
        with:
          repository: srz-zumix/ci-dex-review-contents
          token: ${{ secrets.GitHub_PAT }}
          path: ci-dex/contents
      - uses: docker://kauplan/review2.5
        with:
          entrypoint: bash
          args: -c "cd ci-dex; rake pdf"
      - name: Extract branch name
        id: extract_branch
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      # - uses: actions/upload-artifact@v1
      #   with:
      #     name: ci-dex
      #     path: ci-dex/ci-dex.pdf
      - name: Upload to Google Drive
        uses: satackey/action-google-drive@v1
        with:
          upload-from: ./ci-dex/ci-dex.pdf
          upload-to: /BOOK/techbookfest/techbookfest8/${{ steps.extract_branch.outputs.branch }}
          skicka-tokencache-json: ${{ secrets.SKICKA_TOKENCACHE_JSON }}
          # google-client-id: ${{ secrets.SKICKA_CLIENT_ID }}
          # google-client-secret: ${{ secrets.SKICKA_CLIENT_SECRET }}
